pipeline {
    agent any
    environment{
        NOMBRE='rossana'
        APELLIDO= 'suarez'
        SECRET = credentials('TEST')
    }
    stages{
        stage ('checkout github'){
            steps{
                checkout scm
            }
        }
        stage ('Instalar dependencias'){
            steps{
                sh 'sudo docker --version'
                sh 'npm --version'
            }
        }
        stage ('test'){
            steps{
                echo 'unit test'
            }     
        }
        stage ('build'){
            steps{
                echo 'build'
            }     
        }
        stage ('deploy'){
            steps{
                echo 'deploy'
            }     
        }       
    }
}