pipeline {
    agent any
    environment{
        NOMBRE='rossana'
        APELLIDO= 'suarez'
    }
    stages{
        stage ('checkout github'){
            steps{
                checkout scm
            }
        }  
        stage ('install dependencia'){
            steps{
                sh 'npm install'
            }
        }
        stage ('test'){
            steps{
                sh 'npm run test'
            }
        }
    }
}