version: "3"

services:
  jenkins:
    build: ./jenkins
    image: docker_in_jenkins
    volumes: 
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - "8080:8080"
    env_file: .env

volumes:
  jenkins-data:  




